### ISSUE TITLE
Error with latest pull request

### ISSUE THREAD

**Issue by stephan701** [dcm4che-dockerfiles/dcm4chee-arc-psql#6]
Using default tag: latest
Error response from daemon: manifest for dcm4che/dcm4chee-arc-psql:latest not found

Docker version: 18.06.0-ce
Ubuntu: 18.4

Please advise.  Frustrated.

**Comment by gunterze** [comment]
There is no latest tag, because you have to choose between secured, secured-ui and not secured version anyway. Frustrated by users not reading the [Description at Docker Hub](https://hub.docker.com/r/dcm4che/dcm4chee-arc-psql/) nor the [Wiki](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-on-Docker) nor posting questions first into the [dcm4che user group](https://groups.google.com/forum/#!forum/dcm4che) before opening an issue!
